In [1]:
import pandas as pd

In [2]:
clusters_df = pd.read_csv('out/clusters.csv')
clusters_df.head()

,cluster_id,hits,first_seen,last_seen,source_files,sample_messages,example_exception,levels,incident_hits
0,bcf7ccfa3769e3c11c7d4e5d73836d32162d8e6d,38585,2025-10-20 14:59:08.071000,2026-03-16 13:16:00.012000,2026-02-19/BusinessProcess.log (673); 2025-11-...,"Error in process ""Name = BPMSoftOCCSaveAfkChat...",Npgsql.PostgresException,ERROR:38585,38585
1,fa1582cf0c1899a9a1d4c38fddf955d450c62f01,34178,2025-10-21 10:59:00.041000,2026-03-16 13:16:00.012000,2026-02-19/BusinessProcess.log (657); 2026-02-...,Npgsql.PostgresException (0x80004005): 23503: ...,Npgsql.PostgresException,ERROR:34178,34178
2,586e5fa236eb592c2f837dbb469c327414578dfe,12212,2025-10-20 14:59:08.092000,2026-03-16 13:15:00.044000,2025-10-21/BusinessProcess.log (503); 2025-10-...,Npgsql.PostgresException (0x80004005): 23503: ...,BPMSoft.Core.Process.ProcessComponentSet.Write...,ERROR:12212,12212
3,a41cf6f75ef368f7a4bf4b800bd6eb4d5c58d4ea,7804,2025-10-20 14:59:08.147000,2026-03-16 13:15:00.044000,2026-02-19/BusinessProcess.log (136); 2025-11-...,"Error in process ""Name = BPMSoftOCCCloseOldCha...",Npgsql.PostgresException,ERROR:7804,7804
4,aeca61d6a830206393bf9671a31580cb9527e275,6030,2025-11-01 10:20:03.938000,2026-03-16 13:15:03.942000,2026-02-19/Scheduler.log (125); 2026-02-18/Sch...,"JobFail [className:LlmGigaChatJob, Exception:B...",System.ArgumentNullException,ERROR:6030,6030

In [3]:
events_df = pd.read_csv('out/events.csv')
events_df.head()

,event_id,source_file,timestamp,level,message,stacktrace,normalized_message,signature_hash,request_id,trace_id,exception_type,stack_frames,http_status,is_incident
0,d9a0bf36-b0c2-4067-bc84-fcb90d281b99,2025-10-20/Auth.log,NaN,NaN,"2025-10-20 14:59:07,253 [1/1] obsolete session...",NaN,"<date> <ip>,253 [1/1] obsolete sessions have b...",2b60eede99f9c89654c5248264c9c6b13903be3f,NaN,NaN,NaN,NaN,NaN,False
1,f1d1c64d-7f42-4378-977a-8f7a0153b54d,2025-10-20/Build.log,2025-10-20 15:00:09.313000,INFO,Загрузка схем из базы данных,NaN,загрузка схем из базы данных,74dc46cae21729d05cdc2abdfbf88c36b27d2260,NaN,NaN,NaN,NaN,NaN,False
2,65bd122e-9f9a-4f83-83d5-c3f5967240b0,2025-10-20/Build.log,2025-10-20 15:00:20.692000,INFO,Загрузка схем из базы данных завершена,NaN,загрузка схем из базы данных завершена,84cfe626c1f0897fb0fb9a94eef10b483d0abf77,NaN,NaN,NaN,NaN,NaN,False
3,9c1f4420-9553-4d0e-a937-e4087066b789,2025-10-20/Build.log,2025-10-20 15:00:20.729000,INFO,InitializeContent started at 00:00:11.4172618,NaN,initializecontent started at <ip>.<num>,74e0b3fa35502424cd08ba50107939dfba8a20b2,NaN,NaN,NaN,NaN,NaN,False
4,a2cb5381-1b61-4d9f-ad62-917870bbe94c,2025-10-20/Build.log,2025-10-20 15:00:38.833000,INFO,CopyProjectFile VisualStudioProjectFilePath = ...,NaN,copyprojectfile <token> = [/app/bpmsoft.config...,545247d486d3ec35234b7234453098f271490d9d,NaN,NaN,NaN,NaN,NaN,False