In [2]:
import pandas as pd

In [2]:
clusters_df = pd.read_csv('out/clusters.csv')
clusters_df.head()

,cluster_id,hits,first_seen,last_seen,source_files,sample_messages,example_exception,levels,incident_hits
0,bcf7ccfa3769e3c11c7d4e5d73836d32162d8e6d,38585,2025-10-20 14:59:08.071000,2026-03-16 13:16:00.012000,2026-02-19/BusinessProcess.log (673); 2025-11-...,"Error in process ""Name = BPMSoftOCCSaveAfkChat...",Npgsql.PostgresException,ERROR:38585,38585
1,fa1582cf0c1899a9a1d4c38fddf955d450c62f01,34178,2025-10-21 10:59:00.041000,2026-03-16 13:16:00.012000,2026-02-19/BusinessProcess.log (657); 2026-02-...,Npgsql.PostgresException (0x80004005): 23503: ...,Npgsql.PostgresException,ERROR:34178,34178
2,586e5fa236eb592c2f837dbb469c327414578dfe,12212,2025-10-20 14:59:08.092000,2026-03-16 13:15:00.044000,2025-10-21/BusinessProcess.log (503); 2025-10-...,Npgsql.PostgresException (0x80004005): 23503: ...,BPMSoft.Core.Process.ProcessComponentSet.Write...,ERROR:12212,12212
3,a41cf6f75ef368f7a4bf4b800bd6eb4d5c58d4ea,7804,2025-10-20 14:59:08.147000,2026-03-16 13:15:00.044000,2026-02-19/BusinessProcess.log (136); 2025-11-...,"Error in process ""Name = BPMSoftOCCCloseOldCha...",Npgsql.PostgresException,ERROR:7804,7804
4,aeca61d6a830206393bf9671a31580cb9527e275,6030,2025-11-01 10:20:03.938000,2026-03-16 13:15:03.942000,2026-02-19/Scheduler.log (125); 2026-02-18/Sch...,"JobFail [className:LlmGigaChatJob, Exception:B...",System.ArgumentNullException,ERROR:6030,6030

In [4]:
events_df = pd.read_csv('out/events.csv')
events_df.head(10)

,event_id,source_file,timestamp,level,message,stacktrace,normalized_message,signature_hash,request_id,trace_id,exception_type,stack_frames,http_status,is_incident
0,d9a0bf36-b0c2-4067-bc84-fcb90d281b99,2025-10-20/Auth.log,NaN,NaN,"2025-10-20 14:59:07,253 [1/1] obsolete session...",NaN,"<date> <ip>,253 [1/1] obsolete sessions have b...",2b60eede99f9c89654c5248264c9c6b13903be3f,NaN,NaN,NaN,NaN,NaN,False
1,f1d1c64d-7f42-4378-977a-8f7a0153b54d,2025-10-20/Build.log,2025-10-20 15:00:09.313000,INFO,Загрузка схем из базы данных,NaN,загрузка схем из базы данных,74dc46cae21729d05cdc2abdfbf88c36b27d2260,NaN,NaN,NaN,NaN,NaN,False
2,65bd122e-9f9a-4f83-83d5-c3f5967240b0,2025-10-20/Build.log,2025-10-20 15:00:20.692000,INFO,Загрузка схем из базы данных завершена,NaN,загрузка схем из базы данных завершена,84cfe626c1f0897fb0fb9a94eef10b483d0abf77,NaN,NaN,NaN,NaN,NaN,False
3,9c1f4420-9553-4d0e-a937-e4087066b789,2025-10-20/Build.log,2025-10-20 15:00:20.729000,INFO,InitializeContent started at 00:00:11.4172618,NaN,initializecontent started at <ip>.<num>,74e0b3fa35502424cd08ba50107939dfba8a20b2,NaN,NaN,NaN,NaN,NaN,False
4,a2cb5381-1b61-4d9f-ad62-917870bbe94c,2025-10-20/Build.log,2025-10-20 15:00:38.833000,INFO,CopyProjectFile VisualStudioProjectFilePath = ...,NaN,copyprojectfile <token> = [/app/bpmsoft.config...,545247d486d3ec35234b7234453098f271490d9d,NaN,NaN,NaN,NaN,NaN,False
5,848a9d37-d84c-4612-9804-b1489e704b61,2025-10-20/Build.log,2025-10-20 15:00:38.843000,INFO,DownloadSources Package [Base] Path [/app/BPMS...,NaN,downloadsources package [base] path [/app/bpms...,9063f54a030d9fdc6513775ec87f1d6aa8e714ce,NaN,NaN,NaN,NaN,NaN,False
6,75c5db86-aac0-4810-85ed-00a9416699db,2025-10-20/Build.log,2025-10-20 15:00:52.664000,INFO,DownloadSources Package [NUI] Path [/app/BPMSo...,NaN,downloadsources package [nui] path [/app/bpmso...,36801eb899807429cd19ed28a2dc93d5da7f9e50,NaN,NaN,NaN,NaN,NaN,False
7,2275fcf7-3f76-434e-9c2b-b95765797c4e,2025-10-20/Build.log,2025-10-20 15:00:58.013000,INFO,DownloadSources Package [AnalyticsDashboard] P...,NaN,downloadsources package [analyticsdashboard] p...,a532dcb7a9cb9073bb4e3fe00a1b52729d3d3345,NaN,NaN,NaN,NaN,NaN,False
8,84d35d62-30f4-42e4-9822-31a79c170879,2025-10-20/Build.log,2025-10-20 15:00:58.039000,INFO,DownloadSources Package [Managers] Path [/app/...,NaN,downloadsources package [managers] path [/app/...,198f67ae2c175f3949b5816e31cafd30c8260d23,NaN,NaN,NaN,NaN,NaN,False
9,5b20fbdb-b830-4f04-a9d7-75537f3e8a5c,2025-10-20/Build.log,2025-10-20 15:00:58.050000,INFO,DownloadSources Package [Platform] Path [/app/...,NaN,downloadsources package [platform] path [/app/...,da6349513df47b184c563f007346e461bf3c9845,NaN,NaN,NaN,NaN,NaN,False

In [6]:
events_df.isna().sum()

event_id                    0
source_file                 0
timestamp                 131
level                  559774
message                     0
stacktrace            2146894
normalized_message          0
signature_hash              0
request_id            2263237
trace_id              2263237
exception_type        2148218
stack_frames          2148241
http_status           1703594
is_incident                 0
dtype: int64

In [8]:
from collections import Counter
Counter('rgrsdfdfd')

Counter({'d': 3, 'r': 2, 'f': 2, 'g': 1, 's': 1})

In [7]:
events_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2263237 entries, 0 to 2263236
Data columns (total 14 columns):
 #   Column              Dtype
---  ------              -----
 0   event_id            object
 1   source_file         object
 2   timestamp           object
 3   level               object
 4   message             object
 5   stacktrace          object
 6   normalized_message  object
 7   signature_hash      object
 8   request_id          float64
 9   trace_id            float64
 10  exception_type      object
 11  stack_frames        object
 12  http_status         float64
 13  is_incident         bool
dtypes: bool(1), float64(3), object(10)
memory usage: 226.6+ MB

In [3]:
clusters_df = pd.read_csv('out_single_aspnet/clusters.csv')
clusters_df.head()

,cluster_id,hits,first_seen,last_seen,parser_profiles,source_files,sample_messages,example_exception,levels,incident_hits,confidence_score,confidence_label,clustering_method
0,70671b53e51b77e2d57508e52d9242c15f2cc58c,5,2026-03-11 12:07:09.415000,2026-03-11 12:07:14.672000,log4net_like (5),aspnetcore.log (5),Error unprotecting the session cookie.,System.Security.Cryptography.CryptographicExce...,WARN:5,5,0.925,high,signature
1,99a419925ad7c24a906fff94ee264bddb926ce4e,2,2026-03-11 08:21:15.050000,2026-03-11 08:21:50.750000,log4net_like (2),aspnetcore.log (2),Hosting failed to start,System.Security.SecurityException,ERROR:2,2,0.910,high,signature
2,b0a00e30646ed9a0c86d9ab612dd58e24f963f87,2,2026-03-11 08:21:15.037000,2026-03-11 08:21:50.735000,log4net_like (2),aspnetcore.log (2),Application startup exception,System.Security.SecurityException,FATAL:2,2,0.910,high,signature
3,2269aa1f91d7e17650c15bdd3316c423a0696319,1,2026-03-11 12:07:14.830000,2026-03-11 12:07:14.830000,log4net_like (1),aspnetcore.log (1),An exception was thrown while deserializing th...,Microsoft.AspNetCore.Antiforgery.AntiforgeryVa...,ERROR:1,1,0.905,high,signature
4,d519d774372b497ad934721a29f4b0a38db076a9,1,2026-03-11 08:20:49.723000,2026-03-11 08:20:49.723000,log4net_like (1),aspnetcore.log (1),Hosting failed to start,System.Security.SecurityException,ERROR:1,1,0.905,high,signature

In [4]:
clusters_df = pd.read_csv('out_single_aspnet/events.csv')
clusters_df.head()

,event_id,source_file,parser_profile,timestamp,level,component,message,stacktrace,raw_text,normalized_message,signature_hash,embedding_text,request_id,trace_id,exception_type,stack_frames,http_status,is_incident
0,4b22adc4-0b44-4f5d-b4ab-f0e41e743f18,aspnetcore.log,log4net_like,2026-03-11 08:20:48.390000,WARN,Microsoft.AspNetCore.DataProtection.Repositori...,Storing keys in a directory '/home/ubuntu/.asp...,NaN,"2026-03-11 08:20:48,390 [1] WARN Microsoft.As...",storing keys in a directory '/home/ubuntu/.asp...,67030f73ec951330cb42b1b88694691e4d0d570d,profile=log4net_like || level=warn || componen...,NaN,NaN,NaN,NaN,NaN,False
1,3c16268c-ddb6-4d53-9d4c-a918cb99a140,aspnetcore.log,log4net_like,2026-03-11 08:20:49.617000,FATAL,Microsoft.AspNetCore.Hosting.Diagnostics Start,Application startup exception,System.Security.SecurityException: System logi...,"2026-03-11 08:20:49,617 [1] FATAL Microsoft.A...",application startup exception,9083aea6ae5c185f35ca93aca8fde8c0be17c78c,profile=log4net_like || level=fatal || compone...,NaN,NaN,System.Security.SecurityException,Npgsql.Internal.NpgsqlConnector.Connect | Npgs...,NaN,True
2,2a7a7d30-e02c-4685-8beb-e582b4d7aeec,aspnetcore.log,log4net_like,2026-03-11 08:20:49.723000,ERROR,Microsoft.Extensions.Hosting.Internal.Host Sta...,Hosting failed to start,System.Security.SecurityException: System logi...,"2026-03-11 08:20:49,723 [1] ERROR Microsoft.E...",hosting failed to start,d519d774372b497ad934721a29f4b0a38db076a9,profile=log4net_like || level=error || compone...,NaN,NaN,System.Security.SecurityException,Npgsql.Internal.NpgsqlConnector.Connect | Npgs...,NaN,True
3,78df1eb5-2efa-4289-8fa3-9a1e34d60e21,aspnetcore.log,log4net_like,2026-03-11 08:21:14.469000,WARN,Microsoft.AspNetCore.DataProtection.Repositori...,Storing keys in a directory '/home/ubuntu/.asp...,NaN,"2026-03-11 08:21:14,469 [1] WARN Microsoft.As...",storing keys in a directory '/home/ubuntu/.asp...,67030f73ec951330cb42b1b88694691e4d0d570d,profile=log4net_like || level=warn || componen...,NaN,NaN,NaN,NaN,NaN,False
4,8f0b5fe8-e355-4a5c-8fe7-af98525fe38a,aspnetcore.log,log4net_like,2026-03-11 08:21:15.037000,FATAL,Microsoft.AspNetCore.Hosting.Diagnostics Start,Application startup exception,System.Security.SecurityException: System logi...,"2026-03-11 08:21:15,037 [1] FATAL Microsoft.A...",application startup exception,b0a00e30646ed9a0c86d9ab612dd58e24f963f87,profile=log4net_like || level=fatal || compone...,NaN,NaN,System.Security.SecurityException,Npgsql.Internal.NpgsqlConnector.ReadMessageLon...,NaN,True